In [8]:
import torch.nn as nn
import numpy as np
import torch

In [9]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [10]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [11]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [14]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [19]:
from torch.utils.data import TensorDataset

In [20]:
train_ds = TensorDataset(inputs,targets)

In [24]:
train_ds[:-1]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 74.,  66.,  43.],
         [ 91.,  87.,  65.],
         [ 88., 134.,  59.],
         [101.,  44.,  37.],
         [ 68.,  96.,  71.],
         [ 73.,  66.,  44.],
         [ 92.,  87.,  64.],
         [ 87., 135.,  57.],
         [103.,  43.,  36.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.]]))

In [25]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [26]:
from torch.utils.data import DataLoader

In [27]:
batch_size = 5
train_dl = DataLoader(train_ds , batch_size , shuffle = True)

In [28]:
train_dl

In [33]:
for xb , yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 74.,  66.,  43.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.],
        [ 91.,  87.,  65.]])
tensor([[ 22.,  37.],
        [ 57.,  69.],
        [ 56.,  70.],
        [118., 134.],
        [ 80., 102.]])


In [34]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0179,  0.2796, -0.3636],
        [ 0.5648,  0.4102, -0.3701]], requires_grad=True)
Parameter containing:
tensor([0.1782, 0.2149], requires_grad=True)


In [35]:
model.parameters()

<generator object Module.parameters at 0x000002412CAE7190>

In [37]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0179,  0.2796, -0.3636],
         [ 0.5648,  0.4102, -0.3701]], requires_grad=True),
 Parameter containing:
 tensor([0.1782, 0.2149], requires_grad=True)]

In [38]:
preds = model(inputs)

In [39]:
preds

tensor([[ 4.5833, 53.0154],
        [ 3.1416, 64.0241],
        [18.1123, 82.8532],
        [ 0.5739, 61.7719],
        [ 2.8030, 52.6587],
        [ 4.3216, 53.1700],
        [ 2.4985, 63.2439],
        [17.7666, 83.0479],
        [ 0.8355, 61.6172],
        [ 2.4215, 51.7238],
        [ 3.9401, 52.2351],
        [ 2.8799, 64.1788],
        [18.7554, 83.6334],
        [ 0.9553, 62.7068],
        [ 3.0647, 52.5040]], grad_fn=<AddmmBackward>)

In [42]:
import torch.nn.functional as F

In [43]:
loss_fn = F.mse_loss

In [44]:
loss = loss_fn(preds , targets)
print(loss)

tensor(3852.0928, grad_fn=<MseLossBackward>)


In [45]:
opt = torch.optim.SGD(model.parameters() , lr = 1e-5)

In [51]:
def fit(num_epochs , model , loss_fn , opt , train_dl):
    
    for i in range(num_epochs):
        
        for xb , yb in train_dl:
            
            preds = model(xb)
            
            loss = loss_fn(preds,yb)
            
            loss.backward()
            
            opt.step()
            
            opt.zero_grad()
            
        if (i + 1) % 10 == 0:
            print('{:.4f}' .format(loss.item()))

In [52]:
fit(100 , model , loss_fn , opt , train_dl)

55.9381
34.3010
65.7372
45.2768
37.3274
43.2399
20.2596
43.4114
29.9797
30.1242


In [53]:
preds = model(inputs)

In [54]:
preds

tensor([[ 57.4557,  71.1297],
        [ 79.0294,  96.4033],
        [124.3763, 141.5404],
        [ 23.1105,  40.9358],
        [ 95.3219, 109.4549],
        [ 56.1588,  69.9793],
        [ 78.3192,  95.7072],
        [124.3636, 141.7139],
        [ 24.4074,  42.0862],
        [ 95.9086, 109.9092],
        [ 56.7455,  70.4336],
        [ 77.7325,  95.2530],
        [125.0865, 142.2365],
        [ 22.5238,  40.4815],
        [ 96.6188, 110.6053]], grad_fn=<AddmmBackward>)

In [55]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [56]:
temp = model(torch.tensor([[ 74.,  66.,  43.]]))

In [57]:
temp

tensor([[56.1588, 69.9793]], grad_fn=<AddmmBackward>)

In [58]:
!pip install jovian --upgrade -q

In [59]:
import jovian

<IPython.core.display.Javascript object>

In [60]:
jovian.commit(project='02-linear-regression')

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Updating notebook "yashrsakaria1/02-linear-regression" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/yashrsakaria1/02-linear-regression


'https://jovian.ai/yashrsakaria1/02-linear-regression'